import numpy as np

Project = {'Number_of_Equipment': 1,
 'Equipment1': {'Model_Declarations': {'Type_Equipment': 'STHE',
                                       'Discrete_Values_of_Variables': [[], [], [], [], [], [], [], []],
                                       'Selected_OF': ['TAC_OF']},
                'Model_Parameters': {'mh': 20,
                                     'roh': 750,
                                     'Cph': 2840,
                                     'mih': 0.002,
                                     'kh': 0.19,
                                     'Rfh': 0.0002,
                                     'DPhdisp': 100000,
                                     'mc': 60,
                                     'roc': 995,
                                     'Cpc': 4187,
                                     'mic': 0.0005,
                                     'kc': 0.6,
                                     'Rfc': 0.0007,
                                     'DPcdisp': 100000,
                                     'ktube': 50,
                                     'thk': 0.00165,
                                     'yfluid': 'hot_stream',
                                     'Tube_Method': 'Dittus_Boelter',
                                     'Shell_Method': 'Kern',
                                     'Aexc': 11,
                                     'Tci': 47,
                                     'Tco': 56,
                                     'Thi': 120,
                                     'Tho': 80,
                                     'vsmax': 2,
                                     'vsmin': 0.5,
                                     'vtmax': 3,
                                     'vtmin': 1,
                                     'Retmin': 10000,
                                     'Resmin': 2000,
                                     'Retmax': 5000000,
                                     'Resmax': 100000,
                                     'LBLD': 3,
                                     'UBLD': 15,
                                     'Xp': 0.9,
                                     'F_min': 0.75,
                                     'par_a': 635.14,
                                     'par_b': 0.778,
                                     'pc': 0.15,
                                     'int_rate': 0.1,
                                     'n': 10,
                                     'eta': 0.6,
                                     'Nop': 7500}}}
