import numpy as np

Project = {'Number_of_Equipment': 1,
 'Equipment1': {'Model_Declarations': {'Type_Equipment': 'STHE',
                                       'Discrete_Values_of_Variables': [[0.7874,
                                                                         0.8382,
                                                                         0.889,
                                                                         0.9398,
                                                                         0.9906,
                                                                         1.0668,
                                                                         1.143,
                                                                         1.2192,
                                                                         1.3716,
                                                                         1.524],
                                                                        [0.01905, 0.0254, 0.03175, 0.0381, 0.0508],
                                                                        [1, 2, 4, 6],
                                                                        [1.25, 1.33, 1.5],
                                                                        [1, 2],
                                                                        [1.2195,
                                                                         1.8293,
                                                                         2.439,
                                                                         3.0488,
                                                                         3.6585,
                                                                         4.8768,
                                                                         6.0976],
                                                                        [1,
                                                                         2,
                                                                         3,
                                                                         4,
                                                                         5,
                                                                         6,
                                                                         7,
                                                                         8,
                                                                         9,
                                                                         10,
                                                                         11,
                                                                         12,
                                                                         13,
                                                                         14,
                                                                         15,
                                                                         16,
                                                                         17,
                                                                         18,
                                                                         19,
                                                                         20],
                                                                        [0.25]],
                                       'Selected_OF': ['TAC_OF']},
                'Model_Parameters': {'mh': 110,
                                     'roh': 786,
                                     'Cph': 2177,
                                     'mih': 0.00189,
                                     'kh': 0.12,
                                     'Rfh': 0.0002,
                                     'DPhdisp': 100000.0,
                                     'mc': 228.8,
                                     'roc': 995,
                                     'Cpc': 4187,
                                     'mic': 0.00072,
                                     'kc': 0.59,
                                     'Rfc': 0.0004,
                                     'DPcdisp': 100000.0,
                                     'ktube': 50,
                                     'thk': 0.001225,
                                     'yfluid': 'cold_stream',
                                     'Shell_Method': 'Bell',
                                     'Tube_Method': 'Dewiit_Saunders',
                                     'Aexc': 11,
                                     'Tci': 30,
                                     'Tco': 40,
                                     'Thi': 90,
                                     'Tho': 50,
                                     'vsmax': 2,
                                     'vsmin': 0.5,
                                     'vtmax': 3,
                                     'vtmin': 1,
                                     'Retmin': 10000.0,
                                     'Resmin': 2000.0,
                                     'Retmax': 5000000.0,
                                     'Resmax': 100000.0,
                                     'LBLD': 3,
                                     'UBLD': 15,
                                     'Xp': 0.9,
                                     'F_min': 0.75,
                                     'Nss': 0,
                                     'plbmax1': 52,
                                     'plbmax2': 0.532,
                                     'par_a': 755.781,
                                     'par_b': 0.59,
                                     'pc': 0.1048,
                                     'int_rate': 0.1,
                                     'n': 10,
                                     'eta': 0.6,
                                     'Nop': 7500}}}
